version: '3.4'

services:
  idp.api:
    env_file:
      - ./var1.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:64102;http://+:80
    volumes:
      - /C/ei8/idp:/C/db
      - ~/.aspnet/https:/https:ro
      - ./customsettings.json:/app/appsettings.json
    ports:
      - 192.168.1.110:64102:64102
networks:
    default:
        external:
            name: test_default